server:
  port: 8082

spring:
  application:
    name: AUTHENTICATION-SERVICE
  datasource:
    url: jdbc:postgresql://localhost:5432/bms
    username: postgres
    password: 0000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
logging:
  level:
    org.springframework.security: DEBUG
    com.casestudy: DEBUG